# Generated by Django 4.2.1 on 2023-05-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='SKU')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SA', 'Salida'), ('EN', 'Entrada')], max_length=2, verbose_name='Tipo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartstock.producto', verbose_name='Producto')),
            ],
        ),
    ]
